using Core.Enums;
using System.ComponentModel.DataAnnotations;
using TaskStatus = Core.Enums.TaskStatus;

namespace Core.Models
{
    public class TaskDto
    {
        // Read-only: generated by entity
        public Guid Id { get; private set; }

        [Required(ErrorMessage = "Title is required")]
        public required string Title { get; set; }
        public string? Description { get; set; }

        public TaskStatus? Status { get; set; }
        public TaskPriority? Priority { get; set; }

        public Guid? AssigneeId { get; set; }

        // Read-only: populated from entity
        public string? AssigneeName { get; private set; }
    }
}