using System.ComponentModel.DataAnnotations;

namespace Core.Models
{
    public class TeamMemberDto
    {
        // Read-only: generated by entity
        public Guid Id { get; private set; }


        [Required(ErrorMessage = "First name is required")]
        public required string Name { get; set; }

        [Required(ErrorMessage = "Surname is required")]
        public required string Surname { get; set; }
    }
}